# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-29 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
